## Variabili ambiente

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/NOME_DATABASE
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JWT
# Inserire una chiave segreta lunga almeno 256 bit
jwt.secret=INSERIRE_LA_PROPRIA_SECRET_JWT
jwt.expiration=3600000


# Admin iniziale
admin.email=EMAIL_ADMIN
admin.password=PASSWORD_ADMIN