# Logging
logging.level.root=INFO

logging.level.com.manolo.jobtracker.service=DEBUG
logging.level.com.manolo.jobtracker.controller=INFO
logging.level.com.manolo.jobtracker.repository=INFO
logging.level.com.manolo.jobtracker.exception=WARN

logging.file.name=logs/jobtracker.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{36} | %msg%n

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

