spring.application.name=jobtracker

spring.profiles.active=local

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Admin iniziale
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}